Break tests dependency cycle
- move source to src/
- Use symbolic links for package replicas

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,6 @@
 # This Travis job script has been generated by a script via
 #
-#   haskell-ci 'text.cabal'
+#   haskell-ci '--config=cabal.haskell-ci' 'cabal.project'
 #
 # To regenerate the script (for example after adjusting tested-with) run
 #
@@ -85,6 +85,7 @@ before_install:
   - set -o pipefail
   - TEST=--enable-tests
   - BENCH=--enable-benchmarks
+  - if [ $HCNUMVER -lt 70400 ] ; then BENCH=--disable-benchmarks ; fi
   - HEADHACKAGE=false
   - rm -f $CABALHOME/config
   - |
@@ -117,18 +118,28 @@ install:
   - touch cabal.project
   - |
     echo "packages: ." >> cabal.project
+    echo "packages: tests" >> cabal.project
+    echo "packages: th-tests" >> cabal.project
+    if [ $HCNUMVER -ge 71000 ] ; then echo "packages: benchmarks" >> cabal.project ; fi
   - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text' >> cabal.project ; fi
   - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text-tests' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package th-tests' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text-benchmarks' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(text)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(parsec|text|text-benchmarks|text-tests|th-tests)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
+  - if [ -f "tests/configure.ac" ]; then (cd "tests" && autoreconf -i); fi
+  - if [ -f "th-tests/configure.ac" ]; then (cd "th-tests" && autoreconf -i); fi
+  - if [ -f "benchmarks/configure.ac" ]; then (cd "benchmarks" && autoreconf -i); fi
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
-  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all
-  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all
 script:
   - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
   # Packaging...
@@ -139,15 +150,27 @@ script:
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
   - PKGDIR_text="$(find . -maxdepth 1 -type d -regex '.*/text-[0-9.]*')"
+  - PKGDIR_text_tests="$(find . -maxdepth 1 -type d -regex '.*/text-tests-[0-9.]*')"
+  - PKGDIR_th_tests="$(find . -maxdepth 1 -type d -regex '.*/th-tests-[0-9.]*')"
+  - PKGDIR_text_benchmarks="$(find . -maxdepth 1 -type d -regex '.*/text-benchmarks-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
     echo "packages: ${PKGDIR_text}" >> cabal.project
+    echo "packages: ${PKGDIR_text_tests}" >> cabal.project
+    echo "packages: ${PKGDIR_th_tests}" >> cabal.project
+    if [ $HCNUMVER -ge 71000 ] ; then echo "packages: ${PKGDIR_text_benchmarks}" >> cabal.project ; fi
   - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text' >> cabal.project ; fi
   - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text-tests' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package th-tests' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
+  - if [ $HCNUMVER -ge 80200 ] ; then echo 'package text-benchmarks' >> cabal.project ; fi
+  - "if [ $HCNUMVER -ge 80200 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(text)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(parsec|text|text-benchmarks|text-tests|th-tests)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
@@ -160,11 +183,14 @@ script:
   - ${CABAL} v2-test $WITHCOMPILER ${TEST} ${BENCH} all
   # cabal check...
   - (cd ${PKGDIR_text} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_text_tests} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_th_tests} && ${CABAL} -vnormal check)
+  - if [ $HCNUMVER -ge 71000 ] ; then (cd ${PKGDIR_text_benchmarks} && ${CABAL} -vnormal check) ; fi
   # haddock...
   - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all
   # Building without installed constraints for packages in global-db...
   - rm -f cabal.project.local
   - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
 
-# REGENDATA ("0.10.1",["text.cabal"])
+# REGENDATA ("0.10.1",["--config=cabal.haskell-ci","cabal.project"])
 # EOF
